{
 "title": "FailureSystem",
 "time": { "from": "2026-03-14T18:08:31.297Z", "to": "2026-03-16T18:08:31.297Z" },
 "templating": {
  "list": [
   { "name": "lines", "label": "Lines", "query": { "query": "SELECT name FROM lines " } },
   {
    "name": "machines",
    "label": "Machines",
    "query": {
     "query": "SELECT m.name \r\nFROM machines m\r\nINNER JOIN lines l ON m.line_id = l.id\r\nWHERE l.name IN ('$lines')"
    }
   },
   {
    "name": "symptom",
    "label": "Symptom",
    "query": {
     "query": "SELECT DISTINCT symptom_reported FROM vw_failures_timeline "
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "industrial_failures",
     "rawSql": "SELECT avg(mtbf_days) as \"MTBF Avg\",\r\n        sum(total_failures) as \"Failures\",\r\n        sum(total_downtime_hours) as \"DownTime\"\r\nFROM vw_cost_by_machine\r\nWHERE line_name IN ('$lines') AND machine_name IN ($machines)\r\n"
    }
   ]
  },
  {
   "title": "Failure History",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "industrial_failures",
     "rawSql": "SELECT  line_name as \"Line\", \r\n        machine_name as\"Machine\",\r\n        failure_type as \"Failure Type\", \r\n        symptom_reported as \"Symptom\",\r\n        category as \"Category\",\r\n        severity as \"Severity\"\r\nFROM vw_failures_timeline \r\nWHERE line_name IN ('$lines') AND machine_name IN ($machines) and symptom_reported IN ($symptom)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "industrial_failures",
     "rawSql": "SELECT machine_id,\r\n        status \r\nFROM vw_cost_by_machine \r\nWHERE line_name IN ('$lines') AND machine_name IN ($machines)\r\nORDER BY machine_id"
    }
   ]
  },
  {
   "title": "Category",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "industrial_failures",
     "rawSql": "SELECT category, count(category) FROM vw_failures_timeline \r\nWHERE line_name IN ('$lines') AND machine_name IN ($machines)\r\nGROUP BY category"
    }
   ]
  },
  {
   "title": "Severity",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 7 },
   "targets": [
    {
     "dataset": "industrial_failures",
     "rawSql": "SELECT severity, category, count(severity) FROM vw_failures_timeline \r\nWHERE line_name IN ('$lines') AND machine_name IN ($machines)\r\nGROUP BY category, severity\r\norder by severity, category"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 22, "w": 15, "x": 9, "y": 7 },
   "options": {
    "content": "<iframe src=\"http://localhost:3001/\" width=\"1100\" height=\"800\"></iframe>"
   }
  },
  {
   "title": "Machine Overview",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "industrial_failures",
     "rawSql": "SELECT machine_id,\r\n        machine_name,\r\n        mtbf_days as MTBF,\r\n        total_failures as Failures,\r\n        total_downtime_hours as DownTime\r\nFROM vw_cost_by_machine \r\nwhere line_name IN ('$lines')  AND machine_name IN ($machines)\r\nORDER BY machine_id ASC "
    }
   ]
  }
 ]
}